### PR TITLE
muahahaha

### PR DESCRIPTION
**Pull request by nspauld1**

### CODE REVIEW

**Comment by nspauld1** [comment]
@ConnorGBrewster @homu-salt try

**Comment by homu-salt** [comment]
:hourglass: Trying commit bbb675b with merge b027fe5...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/jspauldo98/Salt/builds/129533222)

**Comment by ConnorGBrewster** [comment]
🎉

**Pull request closed without merging**
