### PR TITLE
Added Ship Assets

### PR DESCRIPTION
**Pull request by Ar13mis**
32x32 versions of the previously mentioned art assets.

testshipblue
testshipred

---
This change is [Reviewable](https://reviewable.io/reviews/boomboxinc/salt/34)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 41b8014 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 41b8014 with merge 85f0add...

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 109f6a6 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 109f6a6 with merge 93f5d5f...

**Comment by homu-salt** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/boomboxInc/Salt/builds/132410653)

**Comment by ConnorGBrewster** [comment]
@Ar13mis the asset path needs to be updated at: https://github.com/boomboxInc/Salt/blob/master/html/src/com/spaulding/salt/GdxDefinition.gwt.xml#L10

**Comment by Ar13mis** [comment]
@ConnorGBrewster fixed the GWT location reference to the asset folder in core

**Comment by ConnorGBrewster** [comment]
@Ar13mis awesome! thanks :D

@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit e77c395 has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit e77c395 with merge e9a6975...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/132429559)

**Pull request merged**
