### PR TITLE
Menu basics

### PR DESCRIPTION
**Pull request by jspauldo98**
Connor is angry

---
This change is [Reviewable](https://reviewable.io/reviews/boomboxinc/salt/36)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 13256cd has been approved by `ConnorGBrewster`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 13256cd with merge 93e47d6...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/132665389)

**Pull request merged**
