### PR TITLE
LibGDX Upgrade

### PR DESCRIPTION
**Pull request by ConnorGBrewster**
r? @jspauldo98

---
This change is [Reviewable](https://reviewable.io/reviews/boomboxinc/salt/31)

### CODE REVIEW

**Comment by jspauldo98** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit d02f3c9 has been approved by `jspauldo98`

**Comment by homu-salt** [comment]
:hourglass: Testing commit d02f3c9 with merge 85fadc7...

**Comment by homu-salt** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/boomboxInc/Salt/builds/130930970)

**Comment by ConnorGBrewster** [comment]
@homu-salt r=jspauldo98

**Comment by homu-salt** [comment]
:pushpin: Commit 350960b has been approved by `jspauldo98`

**Comment by ConnorGBrewster** [comment]
@homu-salt r=jspauldo98

**Comment by homu-salt** [comment]
:pushpin: Commit 5b222c1 has been approved by `jspauldo98`

**Comment by homu-salt** [comment]
:lock: Merge conflict

**Comment by homu-salt** [comment]
:umbrella: The latest upstream changes (presumably #32) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by ConnorGBrewster** [comment]
@homu-salt r=jspauldo98

**Comment by homu-salt** [comment]
:pushpin: Commit 420d328 has been approved by `jspauldo98`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 420d328 with merge d50af85...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/130941615)

**Pull request merged**
