### PR TITLE
homu test

### PR DESCRIPTION
**Pull request by ConnorGBrewster**

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@homu-salt try

**Comment by homu-salt** [comment]
:hourglass: Trying commit 3897c6c with merge 68b86c8...

**Comment by ConnorGBrewster** [comment]
🎉 looks like everything is working again! 💃

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/129550626)

**Pull request closed without merging**
