### PR TITLE
Fix build status link

### PR DESCRIPTION
**Pull request by ConnorGBrewster**

### CODE REVIEW

**Comment by Ar13mis** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit cff71ea has been approved by `Ar13mis`

**Comment by homu-salt** [comment]
:hourglass: Testing commit cff71ea with merge 2d8bd81...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/129556421)

**Pull request merged**
