### PR TITLE
Screen Setup

### PR DESCRIPTION
**Pull request by ConnorGBrewster**
r? @jspauldo98

---
This change is [Reviewable](https://reviewable.io/reviews/boomboxinc/salt/32)

### CODE REVIEW

**Comment by jspauldo98** [comment]
@homu-salt r+

**Comment by homu-salt** [comment]
:pushpin: Commit 6628951 has been approved by `jspauldo98`

**Comment by homu-salt** [comment]
:hourglass: Testing commit 6628951 with merge 047e608...

**Comment by homu-salt** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/boomboxInc/Salt/builds/130937572)

**Pull request merged**
